### ISSUE TITLE
Errornous simplified SVG 

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#93] opened 2016-08-28 21:21 UTC
The SVG file was created originally with Inkscape. I wanted to export it using save->simplified XML. Inkscape generated an errornous svg from this file.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2014-09-17T12:46:05Z
 * owner: suv-lp
 * the launchpad url was https://bugs.launchpad.net/bugs/1369998

**Comment by launchpad-issue-importer** [comment] 2016-08-28 21:24
(by zsolt-sandor)

**Comment by launchpad-issue-importer** [comment] 2016-08-28 21:24
(by zsolt-sandor)
This was the original file, multiple problems happens during export...

**Comment by launchpad-issue-importer** [comment] 2016-08-28 21:24
(by apenner)
could you indicate which OS you are on, and which version of Inkscape?
On Windows 7, Inkscape rev 0.48.5 r10040 I cannot reproduce the problem.
The options I have there are Save As Plain SVG, and Save As Optimized SVG. Both appear to work normally.

**Comment by launchpad-issue-importer** [comment] 2016-08-28 21:24
(by zsolt-sandor)
Hello,

windows 7, latest inkscape downloaded from the website. I can tell you more
tomorrow.

Zsolti

**Comment by launchpad-issue-importer** [comment] 2016-08-28 21:24
(by zsolt-sandor)
Hello,

i could reproduce it on my home computer, too...

Windows 7, Inkscape 0.48.5 r10040

- Open the second svg file
- File->Save as
- Select optimized SVG

Simplifiy colors,
Style to xml
Group collapsing
Enable id stripping
Strip xml prolog

is set

Press ok

Open the newly created svg..

Attached the resoult svg file

**Comment by launchpad-issue-importer** [comment] 2016-08-28 21:24
(by apenner)
- reproduced on Windows 7, Inkscape 0.48.5. The triangle portion of the A letter is misplaced.
- not reproduced on Windows XP, recent trunk revision 13549. However the options available in this output have been significantly rearranged and redefined in trunk, so I'm not sure how to duplicate the original settings you were using.

**Comment by launchpad-issue-importer** [comment] 2016-08-28 21:24
(by zsolt-sandor)
Is there a windows installer available from recent trunk so i can try it
out?
2014.09.16. 23:16 ezt írta ("Alvin Penner" <email address hidden>):

> - reproduced on Windows 7, Inkscape 0.48.5. The triangle portion of the A
> letter is misplaced.
> - not reproduced on Windows XP, recent trunk revision 13549. However the
> options available in this output have been significantly rearranged and
> redefined in trunk, so I'm not sure how to duplicate the original settings
> you were using.
>
> --
> You received this bug notification because you are subscribed to the bug
> report.
> https://bugs.launchpad.net/bugs/1369998
>
> Title:
>   Errornous simplified SVG
>
> Status in Inkscape: A Vector Drawing Tool:
>   New
>
> Bug description:
>   The SVG file was created originally with Inkscape. I wanted to export
>   it using save->simplified XML. Inkscape generated an errornous svg
>   from this file.
>
> To manage notifications about this bug go to:
> https://bugs.launchpad.net/inkscape/+bug/1369998/+subscriptions
>

**Comment by launchpad-issue-importer** [comment] 2016-08-28 21:24
(by zsolt-sandor)
Also, can you please reproduce the same issue with the svg posted in #2. 

This was the bigger file i started to work with, and it has at least 3 different problems:

- The inside triangle of A is moved to the right
- The arrow has like an additional stroke (if i go to stroke and click to none, it disappears)
- The path on the right side also gets wrong

**Comment by launchpad-issue-importer** [comment] 2016-08-28 21:24
(by zsolt-sandor)
Tried out with Inkscape 0.91pre2, and it seems to work perfectly.

**Comment by launchpad-issue-importer** [comment] 2016-08-28 21:24
(by zsolt-sandor)
Just checked with inkscape 0.91pre2

The stroke to the arrow is added, the arrow is wider than original.

**Comment by launchpad-issue-importer** [comment] 2016-08-28 21:24
(by zsolt-sandor)
This is the result, still wrong...

**Comment by launchpad-issue-importer** [comment] 2016-08-28 21:24
(by apenner)
for the file ai_sort_date_asc_e.svg, I can confirm that there is a problem with the conversion of the vertical arrow in the drawing.
It looks as if the stroke width of the arrow has been misinterpreted (too large).

The original drawing had the property stroke:none set for this arrow. The simplified output does not use this property. If I manually copy and paste the stroke:none property into the simplified drawing, then the discrepancy seems to be removed.

**Comment by felixbuenemann** [comment] 2016-08-29 19:57
@Ede123 The problem here seems to be that a path inherits the stroke from the parent group. So if the `stroke:none` style is removed, it applies the stroke from the group.

Code Before optimization:

```svg
<g
   transform="matrix(-0.70710678,0.70710678,-0.70710678,-0.70710678,30.213203,15.807612)"
   id="g2852"
   style="stroke:#646464;stroke-opacity:1;fill:none;fill-opacity:1">
  <path
     style="font-size:medium;font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;text-indent:0;text-align:start;text-decoration:none;line-height:normal;letter-spacing:normal;word-spacing:normal;text-transform:none;direction:ltr;block-progression:tb;writing-mode:lr-tb;text-anchor:start;baseline-shift:baseline;color:#000000;fill:#646464;fill-opacity:1;stroke:none;stroke-width:2;marker:none;visibility:visible;display:inline;overflow:visible;enable-background:accumulate;font-family:Sans;-inkscape-font-specification:Sans"
     d="M 8,5 C 7.9215181,11.081868 7.96875,17.167156 7.96875,23.25 7.3765428,22.643883 6.7685006,22.054381 6.15625,21.46875 L 4.75,22.875 c 1.4506302,1.45063 2.9915849,2.991585 4.25,4.25 1.45063,-1.45063 2.991585,-2.991585 4.25,-4.25 L 11.84375,21.46875 C 11.22461,22.047205 10.630276,22.650974 10.03125,23.25 9.9261582,17.169138 10.189975,11.079187 10,5 z"
     transform="matrix(-0.70710678,-0.70710678,0.70710678,-0.70710678,10.186291,32.54163)"
     id="path2854"
     inkscape:connector-curvature="0"
     sodipodi:nodetypes="cccccccccc" />
</g>
```

After optimization:
```svg
<g id="g2852" transform="matrix(-.70711 .70711 -.70711 -.70711 30.213 15.808)" stroke="#646464" fill="none">
 <path id="path2854" style="block-progression:tb;text-transform:none;text-indent:0" d="m8 5c-0.0785 6.082-0.0312 12.167-0.0312 18.25-0.5923-0.606-1.2003-1.196-1.8126-1.781l-1.4062 1.406 4.25 4.25 4.25-4.25-1.406-1.406c-0.619 0.578-1.214 1.182-1.813 1.781-0.1048-6.081 0.159-12.171-0.031-18.25z" color="#000000" transform="matrix(-.70711 -.70711 .70711 -.70711 10.186 32.542)" fill="#646464"/>
</g>
```

If the `stroke` attribute on the group is removed, the arrow with id `path2854` renders as expected.

**Comment by Ede123** [comment] 2016-08-29 20:49
Thanks for investigating!

Therefore this is yet another duplicate of #22.

**Closed by Ede123** 2016-08-29 20:49 UTC
Labels: launchpad-bug
