### ISSUE TITLE
Save as optimized svg generates invalid svg output

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#96] opened 2016-08-28 21:21 UTC
Steps to reproduce bug:

1. Create new document in inkscape
2. Click the text tool
3. Write something, press return, write something, press return, write something
4. Select the three lines of text and set a new font and font-size
5. Save as optimized svg, and make sure the "group collapsing" option is unchecked, and the "create groups for similar attributes" is checked

The generated output svg has a structure like this:

<svg>
  <text>
    <g>
      <tspan>...</tspan>
      <tspan>...</tspan>
      <tspan>...</tspan>
    </g>
  </text>
</svg>

The g tag in this case makes browsers not render the tspans. It's also invalid svg markup, since <g> isn't allowed as a child of <text>.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-11-16T10:57:32Z
 * owner: suv-lp
 * the launchpad url was https://bugs.launchpad.net/bugs/1516538

**Comment by launchpad-issue-importer** [comment] 2016-08-28 21:25
(by suv-lp)
Reproduced as described with Inkscape 0.91 r13725 and 0.91+devel r14472 on OS X 10.7.5 (both include Scour 0.26+r220).

**Comment by launchpad-issue-importer** [comment] 2016-08-28 21:25
(by tavmjong-free)
Filed bug with Scour:

https://bugs.launchpad.net/scour/+bug/1516607

**Comment by Ede123** [comment] 2016-08-29 00:34
(duplicate of #97)

Fixed in #98

**Closed by Ede123** 2016-08-29 00:34 UTC
Labels: launchpad-bug
