### ISSUE TITLE
Scour inserts inappropriate <g> element when scouring Inkscape multi-line text.

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#97] opened 2016-08-28 21:21 UTC
When the  "group collapsing" option is unchecked, and the "create groups for similar attributes" is checked, Scour inserts a <g> element inside the <text> element when adjacent <tspan>s share the same properties. This prevents the rendering of the <tspan> elements.

See https://bugs.launchpad.net/inkscape/+bug/1516538

Scour should either leave the <tspan>s alone or if all <tspan>s in a <text> element share the same properties, put the properties on the <text> element.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-11-16T12:40:58Z
 * owner: tavmjong-free
 * the launchpad url was https://bugs.launchpad.net/bugs/1516607

**Comment by Ede123** [comment] 2016-08-29 00:34
(duplicate of #96)

Fixed in #98

**Closed by Ede123** 2016-08-29 00:34 UTC
Labels: launchpad-bug
