### ISSUE TITLE
prettyprint adds spaces in text

### ISSUE THREAD

**Issue by JoKalliauer** [scour-project/scour#160] opened 2018-01-03 19:30 UTC
Processing the file [File:Chemie_Orbitale.svg](https://commons.wikimedia.org/wiki/File:Chemie_Orbitale.svg) with
>$ scour [Chemie_Orbitale.svg](https://upload.wikimedia.org/wikipedia/commons/d/d6/Chemie_Orbitale.svg) output.svg

leads to wrong spaces in the text:

minimal working example:
[min.svg.txt](https://github.com/scour-project/scour/files/1601450/min.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg viewBox="0 0 88.596 14.013" xmlns="http://www.w3.org/2000/svg">
 <text x="-.66211" y="9.11719">orbital d<tspan baseline-shift="sub">x<tspan baseline-shift="super" font-size="8">2</tspan>-y<tspan baseline-shift="super" font-size="8">2</tspan></tspan></text>
</svg>

```
![input](https://user-images.githubusercontent.com/15687581/34536166-a008ac8e-f0c4-11e7-94cb-09bc70f16d5e.png)

and the output is:
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg viewBox="0 0 88.596 14.013" xmlns="http://www.w3.org/2000/svg">
 <text x="-.66211" y="9.11719">orbital d
  <tspan baseline-shift="sub">x
   <tspan baseline-shift="super" font-size="8">2</tspan>
-y
   <tspan baseline-shift="super" font-size="8">2</tspan>
  </tspan>
 </text>
</svg>

```
![output](https://user-images.githubusercontent.com/15687581/34536186-b0a1b266-f0c4-11e7-835e-31a53748065e.png)

**Comment by JoKalliauer** [comment] 2018-03-31 14:31
I would like to process [File:Thermal_conductivity.svg](https://commons.wikimedia.org/wiki/File:Thermal_conductivity.svg) but scour adds spaces.


Minimal working example
[min.svg.txt](https://github.com/scour-project/scour/files/1865544/min.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg font-size="24" preserveAspectRatio="xMinYMin meet" viewBox="0 0 856.6 29.609" xmlns="http://www.w3.org/2000/svg">
 <g font-family="'DejaVu Sans Mono'" font-size="24" text-anchor="middle">
  <text x="21.661" y="29.27">10<tspan dy="-16.8" font-size="16.8">-2</tspan></text>
  <text x="185.06" y="29.27">10<tspan dy="-16.8" font-size="16.8">-1</tspan></text>
  <text x="348.36" y="29.27">10<tspan dy="-16.8" font-size="16.8">0</tspan></text>
  <text x="511.66" y="29.27">10<tspan dy="-16.8" font-size="16.8">1</tspan></text>
  <text x="674.96" y="29.27">10<tspan dy="-16.8" font-size="16.8">2</tspan></text>
  <text x="838.36" y="29.27">10<tspan dy="-16.8" font-size="16.8">3</tspan></text>
 </g>
</svg>

```
![min](https://user-images.githubusercontent.com/15687581/38164120-d204bba4-34ff-11e8-9c2e-ffad8a8cb95f.png)


after scour:
[output.svg.txt](https://github.com/scour-project/scour/files/1865550/output.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg font-size="24" preserveAspectRatio="xMinYMin meet" viewBox="0 0 856.6 29.609" xmlns="http://www.w3.org/2000/svg">
 <g font-family="'DejaVu Sans Mono'" font-size="24" text-anchor="middle">
  <text x="21.661" y="29.27">10
   <tspan dy="-16.8" font-size="16.8">-2</tspan>
  </text>
  <text x="185.06" y="29.27">10
   <tspan dy="-16.8" font-size="16.8">-1</tspan>
  </text>
  <text x="348.36" y="29.27">10
   <tspan dy="-16.8" font-size="16.8">0</tspan>
  </text>
  <text x="511.66" y="29.27">10
   <tspan dy="-16.8" font-size="16.8">1</tspan>
  </text>
  <text x="674.96" y="29.27">10
   <tspan dy="-16.8" font-size="16.8">2</tspan>
  </text>
  <text x="838.36" y="29.27">10
   <tspan dy="-16.8" font-size="16.8">3</tspan>
  </text>
 </g>
</svg>
```
![output](https://user-images.githubusercontent.com/15687581/38164140-1af30b72-3500-11e8-889d-10fe4841f798.png)

As you can see scour adds spaces before tspan for `xml:space="default"`

**Comment by Ede123** [comment] 2018-07-01 13:57
This is harder to properly fix as I thought, as it seems renders are handling these border cases differently and we can't know what behavior the user expects.

Let's start with something simple
```SVG
<text>
text1
text2
text3
</text>
```
According to https://www.w3.org/TR/SVG/text.html#WhiteSpace the renderer is supposed to remove all newlines - i.e. the rendered result should be "text1text2text3". Inkscape does this, Firefox renders "text1 text2 text3" instead. This is already problematic as we do not know which behavior the user expected so we can't now wether it's fine to optimize this into `<text>text1text2text3</text>` or not (it is according to spec).

Now add some indentation
```SVG
<text>
    text1
    text2
    text3
</text>
```
According to spec contiguous space characters shall be consolidated, i.e. expected rendering result is "text1 text2 text3". At least now it's clear wether there are spaces intended or not... Here's some (safe) room for optimization in Scour as we currently do not touch contiguous spaces.

Now with the added `<tspan>` it get's more complicated (I'm still trying to figure out that part):
```SVG
<text>
text1
<tspan>text2</tspan>
text3
</text>
```
Should this still render as "text1text2text3"? Inkscape does, Firefox adds spaces...

Right now I'm considering two solutions: 
* Keep the current logic but remove indentation. This will still result in spaces when rendered in Firefox though. Shall we blame this on Firefox? Or do we need a workaround?
* The workaround could be to determine wether the original document had line breaks and optimize accordingly, i.e. stick to the original document. This is ugly, as it basically comes down to assuming `xml:space="preserve"` for text nodes by default (which is wrong). Unfortunately it might be the solution with the least unexpected behavior for users.

**Comment by Ede123** [comment] 2018-07-01 18:21
OK, so I decided to go with a mixture of both:
Optimize text content nodes as much as possible (i.e. replace tabs with spaces, consolidate consecutive spaces, remove leading/trailing spaces) but keep the original structure intact (i.e. do not remove or add newlines).

I'm not 100% satisfied with this solution, but it's the best i can think of right now.

@JoKalliauer (and other interested parties) - could you please test if this fixes the bug reported by you and does not cause regressions or undesired side-effects?

**Comment by JoKalliauer** [comment] 2018-07-01 21:34
@Ede123 
I tried: `pip3 install https://github.com/codedread/scour/archive/master.zip` but nothing changed.

I take the example I created this issue:
>scour [orbital_input.svg](https://github.com/scour-project/scour/files/2153214/orbital_input.svg.txt) [orbital_outpus.svg](https://github.com/scour-project/scour/files/2153215/orbital_outpus.svg.txt)

it still does not work:

----
[orbital_input.svg](https://github.com/scour-project/scour/files/2153214/orbital_input.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg viewBox="0 0 88.596 14.013" xmlns="http://www.w3.org/2000/svg">
 <text x="-.66211" y="9.11719">orbital d<tspan baseline-shift="sub">x<tspan baseline-shift="super" font-size="8">2</tspan>-y<tspan baseline-shift="super" font-size="8">2</tspan></tspan></text>
</svg>
```
![orbital_input](https://user-images.githubusercontent.com/15687581/42138970-25382864-7d86-11e8-92c7-b8b3fc0ce7cc.png)

----

[orbital_outpus.svg](https://github.com/scour-project/scour/files/2153215/orbital_outpus.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg viewBox="0 0 88.596 14.013" xmlns="http://www.w3.org/2000/svg">
 <text x="-.66211" y="9.11719">orbital d
  <tspan baseline-shift="sub">x
   <tspan baseline-shift="super" font-size="8">2</tspan>
-y
   <tspan baseline-shift="super" font-size="8">2</tspan>
  </tspan>
 </text>
</svg>
```
![orbital_outpus](https://user-images.githubusercontent.com/15687581/42138974-39719e78-7d86-11e8-99eb-cf67d8da71bf.png)

----
How the output should look like: (edited by hand)
[orbital_cor.svg.txt](https://github.com/scour-project/scour/files/2153218/orbital_cor.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg viewBox="0 0 88.596 14.013" xmlns="http://www.w3.org/2000/svg">
 <text x="-.66211" y="9.11719">orbital d
<tspan baseline-shift="sub">x
<tspan baseline-shift="super" font-size="8">2</tspan>
-y
<tspan baseline-shift="super" font-size="8">2</tspan>
  </tspan>
 </text>
</svg>

```
![orbital_cor](https://user-images.githubusercontent.com/15687581/42139017-bbc237fc-7d86-11e8-8774-f0277baf5a08.png)

----
Conclusion: Do not add spaces before `<tspan` if `<tspan` does not contain `x="`
(Or do how can I update to the corrected updated scour version?)

**Comment by JoKalliauer** [comment] 2018-07-01 21:59
@Ede123  Sorry didn't read your solution properly, but this issue was about white-space-problems with tspan, not about newlines.

Firefox and Chrome does not understand xml:space properly, so xml:space is **Deprecated since SVG 2** see:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:space
```
This feature has been removed from the Web standards. Though some browsers 
may still support it, it is in the process of being dropped. Avoid using it and 
update existing code if possible; see the compatibility table at the bottom of this 
page to guide your decision. Be aware that this feature may cease to work at any 
time.
```

I know two files, which almost no software can render correctly. (showing text)
[Description](https://commons.wikimedia.org/wiki/File:SVG_Test_TextAlign.svg) and [SVG-file](https://upload.wikimedia.org/wikipedia/commons/a/aa/SVG_test_text_tspan_ws.svg)
[Description](https://commons.wikimedia.org/wiki/File:SVG_test_text_tspan_ws.svg) and [SVG-file](https://upload.wikimedia.org/wikipedia/commons/9/9b/SVG_Test_TextAlign.svg)

But now SVG 1.2 ist the common standard, and therfore xml:space="default" aswell as xml:space="preserve" should work. Maybe it is the best to keep for scour to spaces and linebreak as they are in `<text`

**Comment by Ede123** [comment] 2018-07-02 20:41
@JoKalliauer Sorry, I should've been clearer: The fix is not yet comitted to master (basically to allow for testing) but is open for review as a pull request at #199.

Newlines between <tspan>s (added by scour for pretty-printing) were what caused the issue you reported and with the new behavior (strip all newlines in text nodes) this issue should be fixed while reducing file sizes a bit at the same time.

**Comment by Ede123** [comment] 2018-07-02 20:43
P.S. The new branch is at https://github.com/Ede123/scour/tree/newline_handling, i.e. you can dowload/install it as https://github.com/Ede123/scour/archive/newline_handling.zip

**Comment by JoKalliauer** [comment] 2018-07-02 21:20
@Ede123  Sorry I didn't notice. I never used Python. (Reading parts of a sourcecode I don't know in a language I don't know, therefore I'm to much a beginner.)
But anyway I used `pip3 install https://github.com/Ede123/scour/archive/newline_handling.zip`

And no the original cases are solved, but I might have a new problem (maybe this request is invalid, because Inkscape render input and output the same):

----
[SVG_test_text_tspan_ws.svg](https://upload.wikimedia.org/wikipedia/commons/a/aa/SVG_test_text_tspan_ws.svg)

relevant part:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="460">
<text x="10" y="30">text1<tspan> Text2</tspan></text>
</svg>
```

----
[Output.svg.txt](https://github.com/scour-project/scour/files/2156810/Output.svg.txt)
 relevant part:
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="1200" height="460" xmlns="http://www.w3.org/2000/svg">
 <text x="10" y="30">text1<tspan>Text2</tspan></text>
</svg>

```

----
The first file hast one white space after `<tspan>` but the output-file does not.
Chrome renders them differently, Inkscape renders them the same. I think in this case Chrome is correct.

**Comment by Ede123** [comment] 2018-07-02 21:45
According to https://www.w3.org/TR/SVG/text.html#WhiteSpace the SVG user agent will strip the space when processing the tspan node `<tspan> Text2</tspan>`.

Inkscape has it implemented just like that.

Firefox and Chrome basically ignore this is an SVG document but instead use rules similar to what would apply to HTML content.

As this will always cause inconsistent behavior there's no way we can ensure one or the other (unless we don't touch the content at all - which is not the idea of Scour after all). Therefore I decided to implement behavior that is at least compatible with the SVG spec (and Inkscape). Blame the Browser people for not following the spec, because really - what's the point of a spec if nobody follows it?

**Comment by JoKalliauer** [comment] 2018-07-03 15:13
Sorry, my mistake: I didn't remember https://www.w3.org/TR/SVG/text.html#WhiteSpace properly.
I think the scour-processing seems to work according the definition. (Also as said before by Ede123, some browsers might render them (input and output) differently, which might confuse users, but just because common browsers "ignore" the definition.)
I think we should keep this processing, since it might offer workarounds for wrong rendering in browsers.

**Comment by JoKalliauer** [comment] 2018-07-03 20:11
I have a question about `<text x="1.2,3.4 5.6,7.8" dy="1.2,3.4 5.6,7.8">1  <--zwei Abstände</text>`

The Description
- https://www.w3.org/TR/SVG/text.html#TSpanElementXAttribute
- https://www.w3.org/TR/SVG/text.html#TSpanElementDXAttribute
`If a comma- or space-separated list of n <coordinate>s is provided, then the values represent new absolute X coordinates for the current text position for rendering the glyphs corresponding to each of the first n characters within this element or any of its descendants.`

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg viewBox="0 0 1859.3 1090" xmlns="http://www.w3.org/2000/svg">
 <text transform="matrix(3.1837 0 0 3.1867 102.4 1077.6)" font-size="10.91">
<tspan x="0 7.92 10.92 -10 26.88 34.8 38.88" y="0">Ala    Arg</tspan></text>
</svg>
```

Is Identical with
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg viewBox="0 0 1859.3 1090" xmlns="http://www.w3.org/2000/svg">
 <text transform="matrix(3.1837 0 0 3.1867 102.4 1077.6)" font-size="10.91">
<tspan x="0 7.92 10.92 26.88 34.8 38.88" y="0">AlaArg</tspan></text>
</svg>
```

At least all browsers render the same, is it really according https://www.w3.org/TR/SVG/text.html#TSpanElementXAttribute ? (Then scour-prozessing would also be correct)


Real World file with multiple x:
[Description,Copyright](https://commons.wikimedia.org/wiki/File:Standard_time_zones_of_the_world_(3).svg): and [SVG-File of the World]: [Standard time zones of the world (3).svg](https://upload.wikimedia.org/wikipedia/commons/8/84/Standard_time_zones_of_the_world_%283%29.svg) ;-) ![winking_smiley_yellow_simple svg](https://user-images.githubusercontent.com/15687581/42241722-d0d0260a-7f0b-11e8-8ee7-5284585a56b4.png)

But since svg's of the world are quite large here a smaler pic:
[Description, Copyright](https://commons.wikimedia.org/wiki/File:BLOSUM62.svg) and the file: [BLOSUM62.svg](https://upload.wikimedia.org/wikipedia/commons/5/5a/BLOSUM62.svg)

**Comment by Ede123** [comment] 2018-07-03 20:18
Answer is also in https://www.w3.org/TR/SVG/text.html#WhiteSpace:
> Any features in the SVG language or the SVG DOM that are based on character position number, such as the ‘x’, ‘y’, ‘dx’, ‘dy’ and ‘rotate’ attributes on the ‘text’, ‘tspan’, ‘tref’ and ‘altGlyph’ elements, are based on character position after applying the white space handling rules described here. In particular, if xml:space="default", it is often the case that white space characters are removed as part of processing. Character position numbers index into the text string after the white space characters have been removed per the rules in this section.

**Closed** 2018-07-03 20:56 UTC
Labels: bug
