### ISSUE TITLE
Not valid W3C

### ISSUE THREAD

**Issue by gorantrekant** [scour-project/scour#147] opened 2017-06-19 19:23 UTC
Hi
I'm a graphic worker at https://commons.wikimedia.org/w/index.php?title=Commons:Graphic_Lab/Map_workshop and I have started to use Scour to reduce the file size and to clean up the code from Inkscape. Now I have realized that the code produced by Scour doesn't pass the validating test here https://validator.w3.org/#validate_by_upload.
You can find the three different files here;
http://skulpturalasmycken.se/wikimedia_jobb/plain_inkscape-cleaned-up.svg passed validation
http://skulpturalasmycken.se/wikimedia_jobb/scour-standard-clean-up.svg not passed validation
http://skulpturalasmycken.se/wikimedia_jobb/scour-maximum-clean-up.svg not passed validation
Is this something that could be fixed or just the way it is?
Thanks
/Göran

**Comment by Ede123** [comment] 2017-06-19 21:19
This is a duplicate of #94 and was already fixed in #99.
The fix is part of Scour version 0.35 (released 2016-09-14).

**Closed by Ede123** 2017-06-19 21:19 UTC

**Comment by gorantrekant** [comment] 2017-06-19 21:28
But how can it be fixed when I installed it a week ago?
I installed using the commands on this page https://github.com/scour-project/scour
should that not give me the latest version?

**Comment by Ede123** [comment] 2017-06-19 21:52
If you use Scour from inside Inkscape those steps don't apply as Inkscape (at least on Windows) ships with it's own installation of Python. Even on Linux you have to make sure to install Scour for python2 (`pip2 install ...` I think), not python3!

**Comment by gorantrekant** [comment] 2017-06-19 21:56
No I use it outside Inkscape and I run Linux Ubuntu 16.04. So then its wrong on the installation page?
Will try with pip2, thanks.

**Comment by Ede123** [comment] 2017-06-19 23:50
I don't know how and what you installed (there are multiple instructions on the README), but if you followed any of them properly you should end up with an up-to-date Scour with the mentioned bug fixed.

Maybe try to run `scour --version` to start with since I'm guessing you're just not running whatever version of Scour you might have installed.

**Comment by gorantrekant** [comment] 2017-06-20 17:02
This gives me a version 0.32 and that is after installing pip2.
On the image you can see how I installed it, that is the only information I can see there.
![scour install](https://user-images.githubusercontent.com/29552604/27345633-b965ab34-55ea-11e7-9d7c-5f945cc60be3.png)
I run Ubuntu 16.04.

**Comment by Ede123** [comment] 2017-06-20 18:07
Well, then you're either
* still not running the correct script (try `which scour`) or
* you had scour already installed and did not realize pip did nothing at all (read the status output those tools talk to you!)...  In that case try `pip install --upgrade scour`

The latest version on PyPI is 0.35 and this is what pip will get you when used properly.

I suggest you read some tutorials on
* how to use Python on Ubuntu (notably the difference between python2 and python3, as well as packages installed by your package manager `apt-get` vs packages installed by `pip`)
* how to use `pip` to install and update packages

**Comment by gorantrekant** [comment] 2017-06-20 22:17
I'm really sorry to take your time like this but I have tried to read and understand.
I have now run some commands in the terminal and got some confusing results.
When I list packages I get 0.35 for scour.
When I ask for the scour version I get 0.32.
- pip list
adium-theme-ubuntu (0.3.4)
beautifulsoup4 (4.4.1)
chardet (2.3.0)
cycler (0.9.0)
GDAL (1.11.3)
html5lib (0.999)
httplib2 (0.9.1)
Jinja2 (2.8)
lxml (3.5.0)
MarkupSafe (0.23)
matplotlib (1.5.1)
numpy (1.11.0)
Pillow (3.1.2)
pip (9.0.1)
psycopg2 (2.6.1)
Pygments (2.1)
pyparsing (2.0.3)
pyspatialite (3.0.1)
python-dateutil (2.4.2)
pytz (2014.10)
**scour (0.35)**
setuptools (20.7.0)
six (1.10.0)
unity-lens-photos (1.0)
wheel (0.29.0)

- scour version
**scour 0.32**
Copyright Jeff Schiller, Louis Simard, 2010
Usage: scour [-i input.svg] [-o output.svg] [OPTIONS]
scour: error: Additional arguments not handled: ['version'], see --help

- pip -V
pip 9.0.1 from /home/goran/.local/lib/python2.7/site-packages (python 2.7)

- pip search scour
django-discourse (0) 
discourse_django_sso (0.3.2)
discoursegraphs (0.3.2)
dsegmenter (0.2.12) 
pydiscourse (0.7.0) 
**scour (0.35) 
  INSTALLED: 0.35 (latest)**
tiddlywebplugins.tiddlyspace (1.2.26)
twins (1.1.1)
txDiscourse (0.1.2)

I really hope this can give you something back in regards of problems with installation and so on.

**Comment by Ede123** [comment] 2017-06-20 22:20
> you're still not running the correct script (try which scour)

**Comment by gorantrekant** [comment] 2017-06-21 16:44
Sorry most have missed that.
which scour
/usr/bin/scour

which -a scour
/usr/bin/scour

**Comment by Ede123** [comment] 2017-06-21 17:24
So I'm *guessing* (basically what I already suggested before as one possibility):
* you already have [a version of Scour](https://packages.ubuntu.com/search?keywords=python-scour) installed by your system's package manager
* pip (as far as I know) defaults to `pip install --user` on Ubuntu, i.e. does *not* overwrite the system package
* your path does probably not include the user directory pip has installed the scour script to (probably `~/.local/bin`), which is also the reason the `which` command did not find it

As a result you're probably still running the outdated system-package version instead of the up-to-date version installed by pip.

At this point I'm afraid I have to ask you to start to figure this out on your own (there is more than plenty of information available on the internet that can easily be found with a bit of effort, i.e. [here](https://stackoverflow.com/questions/7143077/how-can-i-install-packages-in-my-home-folder-with-pip) to give you a pointer on where to start) and/or ask in a dedicated Ubuntu forum. Giving general support on how to use Python on Linux/Ubuntu is really not the scope of this issue tracker and at this point it should be clear that this is not a Scour-specific issue...

**Comment by gorantrekant** [comment] 2017-06-21 20:22
Absolutely, I understand and thank you for your help and information.
