### ISSUE TITLE
SyntaxError: expecting a boolean flag; got ('float', u'11')

### ISSUE THREAD

**Issue by JoKalliauer** [scour-project/scour#182] opened 2018-04-03 16:19 UTC
Prozessing [File:Bronzeville.svg](https://commons.wikimedia.org/wiki/File:Bronzeville.svg) with
> scour min.svg output.svg

leads to an error
```bash
Traceback (most recent call last):
  File "C:\Python27\Scripts\scour-script.py", line 11, in <module>
    load_entry_point('scour==0.36', 'console_scripts', 'scour')()
  File "c:\python27\lib\site-packages\scour\scour.py", line 3895, in run
    start(options, input, output)
  File "c:\python27\lib\site-packages\scour\scour.py", line 3863, in start
    out_string = scourString(in_string, options).encode("UTF-8")
  File "c:\python27\lib\site-packages\scour\scour.py", line 3510, in scourString
    cleanPath(elem, options)
  File "c:\python27\lib\site-packages\scour\scour.py", line 2049, in cleanPath
    path = svg_parser.parse(oldPathStr)
  File "c:\python27\lib\site-packages\scour\svg_regex.py", line 160, in parse
    return self.rule_svg_path(next_val_fn, token)
  File "c:\python27\lib\site-packages\scour\svg_regex.py", line 168, in rule_svg_path
    command_group, token = rule(next_val_fn, token)
  File "c:\python27\lib\site-packages\scour\svg_regex.py", line 251, in rule_elliptical_arc
    raise SyntaxError("expecting a boolean flag; got %r" % (token,))
SyntaxError: expecting a boolean flag; got ('float', u'11')
```

minimal working example:
[min.svg.txt](https://github.com/scour-project/scour/files/1871679/min.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg height="200" width="200" xmlns="http://www.w3.org/2000/svg">
 <path d="m195.92 146.13a39.27 41.18 0 11-78.53 0 39.27 41.18 0 1178.53 0z"/>
</svg>
```
![min](https://user-images.githubusercontent.com/15687581/38252556-c0b2d046-3754-11e8-9fb9-62787961c09d.png)

**Comment by Ede123** [comment] 2018-04-03 16:27
Duplicate of #161, with the expected trace-back.
I hope I'll find a bit of time to finally push the fix soon...

**Closed by Ede123** 2018-04-03 16:27 UTC
