### ISSUE TITLE
 Incorrect group optimizing if stroke="none"

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#85] opened 2016-08-28 21:21 UTC
For example a  stroke="none" declaration get removed in the optimization, then sometimes the objects get a stroke if there is a upper-group with stroke="#...". 

For practical example see this version from User:Palosirkka: http://commons.wikimedia.org/wiki/File:Dialog-warning.svg

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2012-09-14T21:12:21Z
 * owner: groby999
 * the launchpad url was https://bugs.launchpad.net/bugs/1051079

**Comment by Ede123** [comment] 2016-08-28 21:48
Duplicate of #22

**Closed by Ede123** 2016-08-28 21:48 UTC
Labels: launchpad-bug
