### ISSUE TITLE
Overwrite svg file if input file is output 

### ISSUE THREAD

**Issue by gistrec** [scour-project/scour#274] opened 2021-04-06 17:52 UTC
Hi, if input and output are the same file, there will be an error `Input filename is the same as output filename`.
But I think, that this is valid case of usage.

**Comment by JoKalliauer** [comment] 2021-04-06 20:00
Imho duplicate of https://github.com/scour-project/scour/issues/129

Be aware the Input-file should be backuped according to @Ede123 https://github.com/scour-project/scour/issues/33#issuecomment-167798462:
>What we could think about is overwriting the input file if no output file name is specified but this might result in really ugly scenarios of data loss, so maybe we should just stick to the current behavior and require the user to provide a valid output file name.

and by @Eitot in https://github.com/scour-project/scour/issues/33#issuecomment-167922813
> But it would be better than overwriting the input file, which I cannot recommend, based on my own experience with this program and others.

**Comment by Ede123** [comment] 2021-05-01 13:09
Yes, this is a duplicate of https://github.com/scour-project/scour/issues/274.

**Comment by Ede123** [comment] 2021-05-01 13:10
Duplicate of #274.

**Comment by Ede123** [comment] 2021-05-01 13:20
Duplicate of #274.

**Closed by Ede123** 2021-05-01 13:20 UTC
