### ISSUE TITLE
Traceback: xml.dom.NotFoundErr with --enable-id-stripping (0.38 regression)

### ISSUE THREAD

**Issue by vbraun** [scour-project/scour#260] opened 2020-08-07 09:26 UTC
This appears to be a 0.38 regression, worked before:
~~~~
$ scour --version
0.38
$ scour --enable-id-stripping -i instagram_icon.svg 
Traceback (most recent call last):
  File "/tools/bin/scour", line 8, in <module>
    sys.exit(run())
  File "/tools/lib/python2.7/site-packages/scour/scour.py", line 4217, in run
    start(options, input, output)
  File "/tools/lib/python2.7/site-packages/scour/scour.py", line 4185, in start
    out_string = scourString(in_string, options).encode("UTF-8")
  File "/tools/lib/python2.7/site-packages/scour/scour.py", line 3823, in scourString
    while removeNestedGroups(doc.documentElement) > 0:
  File "/tools/lib/python2.7/site-packages/scour/scour.py", line 1050, in removeNestedGroups
    g.parentNode.insertBefore(g.firstChild, g)
  File "/tools/lib/python2.7/xml/dom/minidom.py", line 90, in insertBefore
    newChild.parentNode.removeChild(newChild)
  File "/tools/lib/python2.7/xml/dom/minidom.py", line 165, in removeChild
    raise xml.dom.NotFoundErr()
xml.dom.NotFoundErr
~~~~
The svg file in question is attached (rename instagram_icon.svg.txt -> instagram_icon.svg since github does not allow svg attachments)

[instagram_icon.svg.txt](https://github.com/scour-project/scour/files/5040471/instagram_icon.svg.txt)

**Comment by Ede123** [comment] 2020-08-07 21:19
Caused by dd2155e5764d13e03ee3702fdf78d48628a84988. @nthykier can you have a look?

**Comment by nthykier** [comment] 2020-08-12 19:52
Thanks for the notification; I have created #261 which fixes the crash for me.  I have not had time to understand how to create a minimal test case for the issue. However, I figured a published fixed with no test was better than nothing at all.

**Comment by MattiaFailla** [comment] 2020-08-29 08:52
Hi guys, I also ran into this problem. 
If you want I can write some CI to verify that the library behaves as it should, what do you think?

**Comment by Ede123** [comment] 2020-08-29 16:27
@MattiaFailla We already have a good amount of tests and automatic testing via Travis CI. New testcases for increased test coverage are always welcome!

(P.S. I hope to be able to commit the fix next week; I'm on holiday this week and mostly AFK)

**Comment by pbregener** [comment] 2020-09-02 12:06
I also ran into this bug today. Are there any plans for a new/hotfix release including the fix? Or should I pin scour to an older version for the coming weeks/months?

**Closed** 2020-09-02 17:03 UTC
Labels: bug

**Comment by Ede123** [comment] 2020-09-02 17:21
Hotfix release 0.38.1 is out.

**Comment by dmedvinsky** [comment] 2020-09-18 14:42
I'm still getting the exception on `0.38.1.post1`.

Minimal `test.svg`:

```
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 141.732 141.732" xml:space="preserve">
  <g>
    <g clip-path="url(#SVGID_2_)">
      <path d="M1" fill="#fdebc8" stroke="#000" stroke-width=".5" stroke-miterlimit="10"/>
    </g>
    <g clip-path="url(#SVGID_2_)">
      <g>
        <path opacity=".5" clip-path="url(#SVGID_4_)" fill="#fff" d="M1"/>
      </g>
    </g>
  </g>
</svg>
```

```python
class ScourOptions:
    enable_viewboxing = True
    enable_id_stripping = True
    enable_comment_stripping = True
    shorten_ids = True
    indent_type = "none"
    group_collapse = True

s = open("test.svg", 'rb').read()
scour.scourString(s, ScourOptions)
```

raises

```
<ipython-input-41-8388b66e9163> in <module>
----> 1 scour.scourString(s, ScourOptions)

~/.local/lib/python3.8/site-packages/scour/scour.py in scourString(in_string, options)
   3824     # moveAttributesToParentGroup, empty <g>'s may remain.
   3825     if options.group_collapse:
-> 3826         while removeNestedGroups(doc.documentElement) > 0:
   3827             pass
   3828

~/.local/lib/python3.8/site-packages/scour/scour.py in removeNestedGroups(node)
   1056     for child in node.childNodes:
   1057         if child.nodeType == Node.ELEMENT_NODE:
-> 1058             num += removeNestedGroups(child)
   1059     return num
   1060

~/.local/lib/python3.8/site-packages/scour/scour.py in removeNestedGroups(node)
   1048     for g in groupsToRemove:
   1049         while g.childNodes.length > 0:
-> 1050             g.parentNode.insertBefore(g.firstChild, g)
   1051         g.parentNode.removeChild(g)
   1052         _num_elements_removed += 1

/usr/local/lib/python3.8/xml/dom/minidom.py in insertBefore(self, newChild, refChild)
     96                 index = self.childNodes.index(refChild)
     97             except ValueError:
---> 98                 raise xml.dom.NotFoundErr()
     99             if newChild.nodeType in _nodeTypes_with_children:
    100                 _clear_id_cache(self)

NotFoundErr:
```

With `group_collapse = False` no crash happens.
